name: kitty_cat
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  auto_route: ^7.8.4
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_animations: ^1.1.0
  get_it: ^7.6.4
  internet_connection_checker: ^1.0.0+1
  reusable_components:
    git:
      url: https://github.com/ahmedghaly15/Reusable-Components-Package

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/cartoon images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 900

flutter_assets:
  assets_path: assets/
  output_path: lib/src/core/utils/
  filename: app_assets.dart
  field_prefix: null
